### ISSUE TITLE
Code smell

### ISSUE THREAD

**Issue by AndriiOmelchukISG** [UlianaChorna/medicalSystemApi#2]
https://github.com/UlianaChorna/medicalSystemApi/blob/8356e2660a9a57cb3d0e37fc2ac6403d7ce3b72c/src/main/java/com/uliana/MedicalSystemApi/entity/Patient.java#L32-L40

Ніколи не залишайте незрозумілі коментарі в коді. Особливо в master-і

**Comment by UlianaChorna** [comment]
Вже видалила,брала це як приклад json для api , забула видалити(((Дякую)
